#!/usr/bin/env bash

# This is a bash script that transfers a file to the server.
# It accepts four command-line arguments:
# 1. The path to the file to be transferred.
# 2. The IP address of the server.
# 3. The username.
# 4. The path to the SSH private key file.

if [ $# -le 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/; then
	#if [ $? -eq 0 ]; then
		echo "File transferred successfully to $2"
	else
		echo "Transfer failed..."
	fi
fi
