#!/usr/bin/env bash
#a script that takes a string as an argument,
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed,
#pings the IP adress 5 times and.
if [ $# -ne 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
