#!/usr/bin/env bash
#a Bash script that displays a list of currently running processes(all processes, for all users,including those which might not have a
#"TTY", display a user-oriented format and shows process hierarchy.

ps -axuf
