#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd (it desplays only the username, user id, Home directory path for the use)
while IFS= read -r line 
do
	echo "$line" | cut -d ":" -f1,3,6
done < /etc/passwd
