#!/usr/bin/env bash
# this Bash script displays "Best School" 10 times, but for the 9:xth iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -lt 10 ]
do 
	echo "Best School"
	i=$((i+1))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
