#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes (display hours from 0 to 12 and displays minutes from 1 to 59).
i=0
j=1
while [ $i -le 12 ]
do
	echo "Hour: $i"
	while [ $j -lt 60 ]
	do
		echo "$j"
		j=$((j+1))
	done
	i=$((i+1))
	j=1
done
